// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type TargetAccount struct {
	ID              int64          `json:"id"`
	Name            sql.NullString `json:"name"`
	AtmBankCode     sql.NullString `json:"atm_bank_code"`
	BankDetail      sql.NullInt64  `json:"bank_detail"`
	AccountType     string         `json:"account_type"`
	AccountNumber   sql.NullString `json:"account_number"`
	Bank            string         `json:"bank"`
	BankBranch      sql.NullString `json:"bank_branch"`
	Description     sql.NullString `json:"description"`
	TargetType      int64          `json:"target_type"`
	Status          int64          `json:"status"`
	FourthDigit     sql.NullString `json:"fourth_digit"`
	CustomerID      int64          `json:"customer_id"`
	Currency        sql.NullString `json:"currency"`
	AccountTypeCode sql.NullString `json:"account_type_code"`
	Amount          sql.NullString `json:"amount"`
	IsFavorite      sql.NullString `json:"is_favorite"`
}
