// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTargetAccount(ctx context.Context, arg CreateTargetAccountParams) (sql.Result, error)
	DeleteTargetAccount(ctx context.Context, arg DeleteTargetAccountParams) (sql.Result, error)
	GetTargetAccount(ctx context.Context, id int64) (TargetAccount, error)
	GetTargetAccountForUpdate(ctx context.Context, id int64) (TargetAccount, error)
	ListTargetAccount(ctx context.Context, arg ListTargetAccountParams) ([]TargetAccount, error)
	UpdateTargetAccount(ctx context.Context, arg UpdateTargetAccountParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
